### ISSUE TITLE
Calendar UX (Chrome Mac OSX): HTML code when deleting a calendar

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/sogo#139] opened 2015-12-09 23:15 UTC
Warning
Are you sure you want to delete the calendar <em>TEst</em>?

**Comment by extrafu** [comment] 2015-12-11 21:30
Dupe of #177

**Closed by extrafu** 2015-12-11 21:30 UTC

**Comment by dwlfrth** [comment] 2015-12-14 15:09
Actually #177 is a dupe of that one since that one has been filled first ;)
